// Regenerates src/artifacts/*.ts from the Foundry build: `cd contracts && forge build` first.
// The CLI deploys one contract itself (a per-vault PerplAdapter in `agent create`), so only its
// creation bytecode is embedded. Everything else the CLI calls is already deployed.
import { readFileSync, writeFileSync } from "node:fs";

const out = new URL("../../contracts/out/", import.meta.url);
const artifact = (file, name) => JSON.parse(readFileSync(new URL(`${file}/${name}.json`, out)));

const perpl = artifact("PerplAdapter.sol", "PerplAdapter");
writeFileSync(
  new URL("../src/artifacts/PerplAdapter.ts", import.meta.url),
  `// Generated by scripts/artifacts.mjs from contracts/out/PerplAdapter.sol/PerplAdapter.json. Do not edit.
// constructor(IPerplExchange exchange, IERC20 collateral)
export const perplAdapterBytecode = "${perpl.bytecode.object}" as const;
`,
);
console.log("PerplAdapter creation bytecode:", (perpl.bytecode.object.length - 2) / 2, "bytes");
